on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - master

jobs:
  get_version:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[skip deploy]')
    uses: vgarciabnz/workflows/.github/workflows/get-gradle-version.yml@main
    with:
      java_version: 17
      gradle_args: "-PremoveSnapshotSuffix"

  publish:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.get_version.outputs.version }}
