on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[skip deploy]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Print version
        run: ./gradlew printVersion

      - name: Print commit id
        run: git rev-parse HEAD

      - run: |
          git sw automatic
          date > generated.txt
          git add .
          git commit -m "generated"
          git push
