on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - master

jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, '[skip deploy]')
    uses: vgarciabnz/workflows/.github/workflows/publish-gradle-project-release-to-github.yml@main
    with:
      java_version: 17
      gradle_args: "-PremoveSnapshotSuffix"
