on:
  pull_request:

jobs:
  get_version:
    uses: vgarciabnz/workflows/.github/workflows/get-gradle-version.yml@main
    with:
      java_version: 17
      gradle_args: "-PremoveSnapshotSuffix"

  release:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: Print branch info
        run: ./gradlew printBranchInfo
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_BRANCH_DEST: ${{ github.base_ref }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}

      - run: echo ${{ needs.get_version.outputs.version }}

