on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch info
        run: ./gradlew printBranchInfo
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_BRANCH_DEST: ${{ github.base_ref }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}

      - run: echo ${{ needs.get_version.outputs.version }}

