on:
  workflow_dispatch:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || (github.event_name == 'workflow_dispatch' && github.ref_name == 'github-release') }}
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref }}

  second:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip publish]') }}
    steps:
      - run: echo ${{ github.event_name }}
