on:
  workflow_dispatch:
  pull_request:

jobs:
  publish:
    uses: vgarciabnz/workflows/.github/workflows/publish-dokka-to-github-pages.yml@main
    with:
      java_version: 21
      gradle_args: "-PremoveSnapshotSuffix"
      output_folder: "dokka"
